Update README to note the charm is deprecated
canonical/charm-kubernetes-service-checks pull request #12
Opened 2024-06-10 22:43 UTC by aieri

2024-06-10 22:45 UTC, aieri commented
Note that the markdown used is GH-specific: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

2024-06-11 00:43 UTC, samuelallan72 requested changes

2024-06-11 00:43 UTC, samuelallan72 commented on README.md
> +
This doesn't render the icon (see [rich view](https://github.com/canonical/charm-kubernetes-service-checks/blob/a9ed4e27ba395d0e0da7feca72e083d177a64b3d/README.md)) - I'm guessing the blank line between this and the content needs to be removed?

2024-06-11 00:43 UTC, samuelallan72 commented on README.md
> +> This is a deprecated charm that only supports Kubernetes ≤ 1.28 and does not integrate with the Canonical Observability Stack. Please rely on native COS integration offered by the Kubernetes charms
It could be useful to add inline links to COS and the relevent docs for supported charms for monitoring k8s deployments.

2024-06-18 23:32 UTC, aieri commented on README.md
> +
ugh yes you're right

2024-06-19 00:05 UTC, samuelallan72 approved these changes
Thanks, LGTM :)

2024-06-19 08:50 UTC, rgildein approved these changes

2024-06-20 04:38 UTC, merged